kind: Deployment
apiVersion: apps/v1
metadata:
  name: dvwa
spec:
  template:
    metadata:
      labels:
        app: dvwa
    spec:
      containers:
      - name: dvwa
        image: gru.ocir.io/fortinetoraclecloud1/dvwa-fgallego:<TAG>
        imagePullPolicy: "Always"
      imagePullSecrets:
      - name: ocirsecret
  selector:
    matchLabels:
      app: dvwa
---
kind: Service
apiVersion: v1
metadata:
  name: dvwa
spec:
  type: LoadBalancer
  selector:
    app: dvwa
  ports:
  - name: http
    port: 8081
    targetPort: 80
